name: Go
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Publish Image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    timeout-minutes: 2
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build Artifact
        run: go build -o listener .

      - uses: actions/upload-artifact@v2-preview
        with:
          name: listener-${{ matrix.os }}
          path: listener
