name: Go
on: push
jobs:
  build:
    name: Build & Publish Image
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Build+Push
        uses: docker/build-push-action@v1
        with:
          username: "coip"
          password: ${{ secrets.pkgpat }}
          repository: coip/banalplatitude
          dockerfile: /github/workspace/Dockerfile
          registry: docker.pkg.github.com
          tags: latest