name: Go
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Publish Image
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build+Push
        uses: docker/build-push-action@v1.0.1
        with:
          username: "coip"
          password: ${{ secrets.pkgpat }}
          repository: coip/banalplatitude/listener
          registry: docker.pkg.github.com
          tags: latest