name: Go
on: push
jobs:
  build:
    name: Build & Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Build+Push
        uses: docker/build-push-action@v1
        with:
          username: "coip"
          password: ${{ secrets.pkgpat }}
          repository: coip/banalplatitude
          tags: latest